version: '0.2'
addresses:
  kanej@mailscript.io:
    keys:
      - name: owner
        read: true
        write: true
triggers:
  - name: all-test
    composition:
      - and:
          - and-test
          - or-test
  - name: and-test
    composition:
      - and:
          - domain-test
          - sent-to-me
  - name: domain-test
    composition:
      - criteria:
          domain: github.com
  - name: or-test
    composition:
      - or:
          - domain-test
          - sent-to-me
  - name: sent-to-me
    composition:
      - criteria:
          sentTo: kanej@mailscript.io
actions:
  - name: dentist
    type: sms
    config:
      number: '+447747801325'
      text: '{{subject}}'
  - name: both
    list:
      - send-01
      - send-02
  - name: send-02
    type: mailscript-email
    config:
      subject: 'An email again: {{msg.subject}}'
      type: send
      html: <p>More emails</p>
      from: kanej@mailscript.io
      to: example@example.com
      key: owner
  - name: send-03
    type: mailscript-email
    config:
      subject: 'More: {{msg.subject}}'
      type: send
      html: <p>More emails</p>
      from: kanej@mailscript.io
      to: example2@example.com
      key: owner
  - name: all
    list:
      - both
      - send-03
  - name: send-01
    type: mailscript-email
    config:
      subject: 'An email was received: {{msg.subject}}'
      type: send
      html: <p>More emails! Because of the additions.</p>
      from: kanej@mailscript.io
      to: john.kane84@gmail.com
      key: owner
workflows:
  - name: send-test
    input: kanej@mailscript.io
    trigger: sent-to-me
    action: send-01

