version: '0.2'
addresses:
  kanej@mailscript.io:
    keys:
      - name: owner
        read: true
        write: true
triggers:
  - name: and-test
    composition:
      - and:
          - domain-test
          - sent-to-me
  - name: domain-test
    composition:
      - criteria:
          domain: github.com
  - name: or-test
    composition:
      - or:
          - domain-test
          - sent-to-me
  - name: or-test2
    composition:
      - or:
          - domain-test
          - sent-to-me
  - name: sent-to-me
    composition:
      - criteria:
          sentTo: kanej@mailscript.io
actions:
  - name: forward-01
    type: mailscript-email
    config:
      forward: john.kane84@gmail.com
      type: forward
      from: kanej@mailscript.io
      key: owner
  - name: send-01
    type: mailscript-email
    config:
      subject: 'An email was received: {{msg.subject}}'
      type: send
      html: <p>More emails</p>
      from: kanej@mailscript.io
      to: john.kane84@gmail.com
      key: owner
workflows:
  - name: send-test
    input: kanej@mailscript.io
    trigger: sent-to-me
    action: send-01
