version: "0.2"
addresses:
  $username@mailscript.com:
    keys:
      - name: owner
        read: true
        write: true
workflows:
  - name: save-pdf-to-google-drive
    input: $username@mailscript.com
    action: save-pdf-to-google-drive
actions:
  - name: save-pdf-to-google-drive
    type: webhook
    config:
      body: |
        {
          "attachments": "{{msg.attachments}}",
          "driveStoragePath": "path-to-save-pdfs-in-for-google-drive",
          "credsClientId": "service-account-id",
          "credsPrivateKey": "service-account-private-key"
        }
      url: "https://write-to-csv-endpoint.url"
      opts:
        headers:
          Content-Type: application/json
        method: POST
