version: "0.2"
addresses:
  $username@mailscript.com:
    keys:
      - name: owner
        read: true
        write: true
workflows:
  - name: auto reply to first time sender
    input: $username@mailscript.com
    trigger: first-time-trigger
    action: first-time-reply
triggers:
  - name: first-time-trigger
    composition:
      - criteria:
          firstTimeSender: true
actions:
  - name: first-time-reply
    type: mailscript-email
    config:
      from: $username@mailscript.com
      key: owner
      type: reply
      text: I will get back to you as soon as possible
