version: "0.1"
addresses:
  address@mailscript.com:
    keys:
      - name: owner
        read: true
        write: true
accessories:
  - name: address@mailscript.com
    type: mailscript-email
    address: address@mailscript.com
    key: owner
workflows:
  - name: auto reply to first time sender
    trigger:
      accessory: address@mailscript.com
      config:
        criterias:
          - firstTimeSender: true
    actions:
      - accessory: address@mailscript.com
        config:
          type: reply
          text: I will get back to you as soon as possible
