version: "0.2"
addresses:
  $username@mailscript.com:
    keys:
      - name: owner
        read: true
        write: true
workflows:
  - name: Build failed to discord#channel
    input: $username@mailscript.com
    trigger: github-build-failed
    action: github-build-failed-discord-action
triggers:
  - name: github-build-failed
    composition:
      - criteria:
          from: notifications@github.com
          subjectContains: run failed
actions:
  - name: github-build-failed-discord-action
    type: webhook
    config:
      body: |
        {
          "content": "Build failed: {{msg.subject}}"
        }
      url: "https://discord.webhook"
      opts:
        headers:
          Content-Type: application/json
        method: POST
