version: "0.2"
addresses:
  $username@mailscript.com:
    keys:
      - name: owner
        read: true
        write: true
workflows:
  - name: attachments
    input: $username@mailscript.com
    trigger: attachments-trigger
    action: attachments-webhook-action
triggers:
  - name: attachments-trigger
    composition:
      - criteria:
          hasAttachments: true
actions:
  - name: attachments-webhook-action
    type: webhook
    config:
      body: |
        {
          "attachments": "{{msg.attachments}}"
        }
      url: "https://endpoint.url"
      opts:
        headers:
          Content-Type: application/json
        method: POST
