version: "0.2"
addresses:
  $username@mailscript.com:
    keys:
      - name: owner
        read: true
        write: true
workflows:
  - name: save-email-to-google-drive
    input: $username@mailscript.com
    action: save-pdf-to-google-drive
actions:
  - name: save-email-to-google-drive
    type: webhook
    config:
      body: |
        {
          "content": "{{all}}",
          "driveStoragePath": "storage/path/on/google/drive",
          "googleDriveAuth": "{{integrations.google}}"
        }
      url: "https://us-central1-mailscript-firebase.cloudfunctions.net/googleDriveEmailUploader"
      opts:
        headers:
          Content-Type: application/json
        method: POST
