name: Pull requests

on:
  pull_request:
    branches:
      - main

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install
        run: yarn
      - name: Lint
        run: yarn format:check && npx eslint src/**/*.ts && npx tsc --noEmit
      - name: Test
        run: yarn test
